[workspace]
authors = ["CodeMan-9527 <codeman9527@gmail.com>"]
name = "dl-template-cpu"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[dependencies]
# We need a python version that is compatible with pytorch
python = ">=3.13.5,<3.14"
numpy = ">=2.3.2,<3"
pandas = ">=2.3.1,<3"
jupyterlab = ">=4.4.5,<5"
matplotlib = ">=3.10.5,<4"

[pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cpu" }

[tasks]
lab = "jupyter lab --notebook-dir=."



